### ISSUE TITLE
pkgj config became obsolete and prone to cause user errors

### ISSUE THREAD

**Issue by TheRadziu** [theheroGAC/Autoplugin#102]
Since v0.44 pkgj now uses hardcoded NPS urls [+Comp packs] by default, but they are still overwriteable by using config.txt and this is why it should be removed from autoplugin,as it might cause issues for end users. 

Also, rest of the config.txt [besides urls] is default, so no need to include it either.

**Comment by bamhm182** [comment]
I don't see how keeping the option would cause issues for users. Ideally, the built in config should be the same as the one in Autoplugin. If both PKGj and Autoplugin stop getting updated and the nps site goes down, then having the Autoplugin option would at least get the config file set up for the user to edit it. Perhaps a message after you click on it (similar to the SD2VITA screen) stating that it probably isn't necessary would be a good idea.

**Comment by blastrock** [comment]
These URL have changed multiple times already. By having them with default values in pkgj, we can update these values by just asking users to update pkgj. If they are set in the config file, pkgj will always use the ones set in the config, and when a site goes down users will have to update their config manually, which was proven difficult until now.

**Comment by theheroGAC** [comment]
I leave the option in Autoplugin?

**Comment by bamhm182** [comment]
I think both blastrock and TheRadziu are saying to remove it. After time thinking about it, I agree. If for some reason in the future PKGj stops updating and the defaults go bad, it can be readded to Autoplugin.

**Comment by theheroGAC** [comment]
https://twitter.com/TheheroGAC/status/1082729169233080326
Users say not to cancel this function
I create something to update the config.txt file directly from the site :)

**Comment by TheRadziu** [comment]
you didn't mention why you want to do it and this is why I'd say those results are invalid.

**Comment by bamhm182** [comment]
What if we place a warning before placing the config. "As of PKGj v0.44, config files are no longer necessary. Try using it without this file. If you are still having issues, install the config file by pressing x. Press o to delete." Or something along those lines.

**Comment by theheroGAC** [comment]
> you didn't mention why you want to do it and this is why I'd say those results are invalid.
> 
> run the survey again but now explain what will happen if you leave it like this and why we suggest you to remove it in a first place.

no problem delete in the next release

**Comment by bamhm182** [comment]
I figure worst case scenario, if it is needed in the future, it will be trivial to add back in.

**Comment by theheroGAC** [comment]
Yes :)

**Comment by theheroGAC** [comment]
new autoplugin available https://github.com/theheroGAC/Autoplugin/releases/download/3.67/Autoplugin.vpk
@TheRadziu @bamhm182
