### ISSUE TITLE
Autoplugin is becoming a little crowded

### ISSUE THREAD

**Issue by bamhm182** [theheroGAC/Autoplugin#106]
With all of the wonderful additions that Autoplugin has seen, I've begun to notice it becoming more and more crowded. I'm wondering if something like an "Extras" menu would be a welcome idea. I started playing around with the idea to get more familiar with .lua and came up with the following example.

![2019-01-08-194008](https://user-images.githubusercontent.com/920269/50868729-dc0a9980-137e-11e9-8745-f6bdb3f6852e.png)
![2019-01-08-194017](https://user-images.githubusercontent.com/920269/50868731-ddd45d00-137e-11e9-8224-51b4a1d8eddb.png)

If you hate it, no problem! If you like the idea, let me know and I'll submit a PR.

**Comment by theheroGAC** [comment]
Yes very good idea.thank you

**Comment by bamhm182** [comment]
No problem. Glad I could help. Keep up the great work!

**Comment by theheroGAC** [comment]
Thanks for all the changes you have made. If you want to add something missing, you can add them

**Comment by bamhm182** [comment]
No problem. Autoplugin has been toward the top of my must have homebrew since I started getting into hacking the Vita a few months ago so I'm glad to help!

I have a couple ideas on things I can add or improve upon.

**Comment by bamhm182** [comment]
I'm so sorry! I don't know how I screwed that up. I'll look back over my code and 3.67 and see what happened. I'll thought I was taking care to ensure nothing would break, but it looks like I missed something. I'll take care to check that everything is functional in the future.

It appears as though everything is fixed now. Is there anything you need me to do?

**Comment by theheroGAC** [comment]
what can we still add to autoplugin? perhaps the plugins in alphabetical order with a search field

**Comment by bamhm182** [comment]
I was thinking about that as well. It would be helpful as we get more and more plugins. With my question though, I meant specifically toward what I broke. I don't see anything left to do. It looks like you took care of it, but I wanted to ask.

**Comment by caghandemir** [comment]
Here's an idea. Set up a Github Pages and add the plugins to a XML file there (ideally set to get the latest version from GitHub), download the XML on the app and parse it to create a list. THIS WOULD ALLOW YOU TO NOT INCLUDE BINARIES FOR THE PLUGINS THEMSELVES STEALING DOWNLOADS AND VIOLATING GPL AT THE SAME TIME MAYBE?

**Comment by bamhm182** [comment]
Do you intend to come off angry with the capitals?

Either way, this doesn't sound like a bad idea. It would allow Autoplugin to be a little lighter too.

**Comment by bamhm182** [comment]
I honestly just started helping out with Autoplugin on this week. I'm sure theHeroGAC has heard of it.

**Comment by theheroGAC** [comment]
> È _onestamente_ non aveva pensato di esso? Era stato proposto sul subreddit più volte.

You can do a test version and test everything. It's a great idea

**Comment by bamhm182** [comment]
I figured out what I did wrong. I modified the code that scrolls through the table. I thought that it would go to the bottom of the entire list, but it only went to the bottom of the currently visible items. This made it so you could only select the first 12 plugins.

The original issue has been resolved. All side issues addressed in this issue have been put into their own issues. Closing.
