### ISSUE TITLE
List Autoplugin in VitaDB

### ISSUE THREAD

**Issue by robsdedude** [theheroGAC/Autoplugin#109]
How about getting this nice piece of Homebrew listed over at [VitaDB](https://vitadb.rinnegatamante.it/#/instructions) so that it can be easily installed via e.g. Vita Homebrew Browser.

**Comment by theheroGAC** [comment]
Unfortunately the developer rinnegatamante does not want. He says that the development language (Onelua) used does not like it

**Comment by theheroGAC** [comment]
Use https://store.brewology.com/vita/whatsnew.php?lang=

**Comment by bamhm182** [comment]
It isn't that VitaDB doesn't work with onelua apps, it's that it isn't open source and that rubs him the wrong way. He also doesn't allow GameMaker games on the VitaDB.

http://wololo.net/talk/viewtopic.php?t=47915&start=10

I too would love to see Autoplugin in VHBB. I'll try and see if it is within my capabilities to add the ability to specify sources other than VitaDB to get Homebrew from. It would be awesome to be able to create a GitHub project that acted as a second VitaDB that VHBB could pull from.

**Comment by bamhm182** [comment]
Oh! I stand corrected! The post I got that link from said that he was also against GameMaker since it wasn't open source.

With that in mind, have we tried submitting Autoplugin to VitaDB recently? I wonder if it being open source would be enough to get on there.

**Comment by robsdedude** [comment]
I have tried to do so. He's boycotting ONElua. And was pretty rude to me for just asking.
https://github.com/Rinnegatamante/VitaDB/issues/3
https://github.com/Rinnegatamante/VitaDB/issues/11

And instead of explaining it to me I had to search quite a lot to find this:
http://wololo.net/talk/viewtopic.php?t=47915&start=10

Baseline: it won't happen.
