### ISSUE TITLE
Deleted gamesd.skprx command

### ISSUE THREAD

**Issue by cloudstrife999** [theheroGAC/Autoplugin#11]
Even while selecting ur0 and gamesd plugin by pressing up button all plugins updated but deleted gamesd.skprx plugin comment line leading to sd2vita not being detected.. This is insane why give such an option then?!!! Please rectify in next update.

**Comment by theheroGAC** [comment]
you can find a backup of the config file in the ur0:tai (config_backup.txt) folder

**Comment by cloudstrife999** [comment]
true but it is an issue. why bother to uograde then?

**Comment by theheroGAC** [comment]
ok and sorry for the inconvenience I will update the program. What option does it have problems? (ur0: tai for SD2VITA?)

**Comment by cloudstrife999** [comment]
correct. sorry if i sounded rude. thanks. love the program.

**Comment by theheroGAC** [comment]
New version is available.Thank you https://github.com/theheroGAC/Autoplugin/releases/tag/1.11
