### ISSUE TITLE
simplified Chinese

### ISSUE THREAD

**Issue by liuxd128** [theheroGAC/Autoplugin#119]
Hello! Thank you for everything! What is the reason for the absence of characters in simplified Chinese? My English is not good, online translation, thank you!

**Comment by liuxd128** [comment]
> 字符是否缺失或是英文单词？如果单词是英文，您可以分叉此存储库，进行翻译，然后提交拉取请求。我一直试图想办法让翻译更容易，但还没有完成。
> 
> 如果这有帮助，请告诉我。

Thank you for your answer! Character missing, shown as underscore

**Comment by bamhm182** [comment]
What character? Can you type the sentence here with the underscore and again with the correct character?

**Comment by liuxd128** [comment]
> What character? Can you type the sentence here with the underscore and again with the correct character?

All? Or a simple example?
Example: 
     Correct:     卸载插件                 App Displays:           卸_插件
                      检查插件更新                                        _插件更新
Is it the reason for simplified Chinese libraries? Traditional Chinese can be displayed normally. However, many plug-ins in traditional Chinese are described in English.

**Comment by yexun1995** [comment]
The traditional Chinese translation file is not updated for a long time.
You need a font.pgf file to use the CHS translation file.Check README.md file of this project.

**Comment by liuxd128** [comment]
> 繁体中文翻译文件很长时间没有更新。繁体中文翻译文件很久没有更新了。
> 
> 你需要一个font.pgf文件来使用CHS 
> 翻译。请查看这个项目的README.md文件。你需要一个字体。毕业文件来使用简体中文翻译。请查看本项目的README.md文件。


Thank you very much. It's settled. Thank you for your Sinicization
