### ISSUE TITLE
Update all languages

### ISSUE THREAD

**Issue by theheroGAC** [theheroGAC/Autoplugin#120]
Please update new file english.txt @yexun1995 @bamhm182 @Umineko1993 @gvaldebenit @chronoss09 @Schn1ek3 
https://github.com/theheroGAC/Autoplugin/blob/master/lang/english_us.txt

**Comment by Schn1ek3** [comment]
[german_de.txt](https://github.com/theheroGAC/Autoplugin/files/2758825/german_de.txt)

here the Update from german language :)

**Comment by theheroGAC** [comment]
Thank you

**Comment by theheroGAC** [comment]
Thank you @ONElua

**Comment by LimonChoms** [comment]
Hello, this is a translation of Traditional Chinese. Can u add it?
[Chinese_t.txt](https://github.com/theheroGAC/Autoplugin/files/2775415/Chinese_t.txt)

**Comment by theheroGAC** [comment]
thank you @LimonChoms

**Comment by theheroGAC** [comment]
Thank you @yexun1995

**Comment by yexun1995** [comment]
A fixed version of f42941282012901e81b4df8389b7b558419f390b
If LimonChoms doesn't fix it before the next release, you can use this version. 
[CHINESE_T.lua.txt](https://github.com/theheroGAC/Autoplugin/files/2795603/CHINESE_T.lua.txt)

**Comment by Bratislavaenslip** [comment]
Fixed compatibility issues with my previous translation
[FRENCH.txt](https://github.com/theheroGAC/Autoplugin/files/2810521/FRENCH.txt)

**Comment by gvaldebenit** [comment]
I would like to know how much space is between the line of translation and the string, to reformat spanish.lua and avoid issues like last time

**Comment by gvaldebenit** [comment]
There were conflicts last time I PR'ed. It was because of spaces, so new file ended a mess with spaces due to manual changes.

**Comment by gvaldebenit** [comment]
ok, thanks for the info. I tried it so i will make a PR

**Comment by yexun1995** [comment]
[CHINESE_T.lua.txt](https://github.com/theheroGAC/Autoplugin/files/2843591/CHINESE_T.lua.txt)
Please use this file if LimonChoms does not push updates before the next release.

**Comment by Weediee** [comment]
Here is Polish translation, will edit later for Polish font for example ęążćłó.
[polish.txt](https://github.com/theheroGAC/Autoplugin/files/2849058/polish.txt)

**Comment by sakirasci** [comment]
Here is the Turkish translation.
[TURKISH.zip](https://github.com/theheroGAC/Autoplugin/files/2870318/TURKISH.zip)

**Comment by theheroGAC** [comment]
thank you @sakirasci

**Comment by IgrovoeShow** [comment]
Hey! Here's Russian translation of the app. I made it by transferring .lua from PSVita via VitaShell and editing on a PC. When testing, it showed no problems. Thx for your work!
[RUSSIAN.zip](https://github.com/theheroGAC/Autoplugin/files/2882533/RUSSIAN.zip)

**Comment by theheroGAC** [comment]
Thank you @IgrovoeShow :)

**Comment by indoril667** [comment]
Sorry for bad English,
in Polish translation file in line 115 is missing this sign at end: 

> "

 and app wont start, after i edit file and add " app start and work good.

**Comment by theheroGAC** [comment]
fix in new version 3.80 thank you
