### ISSUE TITLE
In-App Translation

### ISSUE THREAD

**Issue by bamhm182** [theheroGAC/Autoplugin#129]
It would be awesome if we could translate the various menu options in-app and easily get them to the maintainers of Autoplugin.

I haven't started taking a crack at this yet, but I'm thinking it would take a pretty big refactor in how the languages work. I'm thinking if there were a giant array like:

`language = {  
MENU_TITLE="Autoplugin",  
MENU_VITA_PLUGINS="Plugins for Vita"   
}`

We could call them like os.message(language[MENU_TITLE])

In the menu, there could be a translate option that loads the English language, your current language file, and your personal translations like this:

`
do("english.lua")  
local english=language  
do(os.language()..".lua")  
local official=lanugage  
do("personal/"..os.language()..".lua")  
local yours=language  
`
From there, it would iterate them into a table and you could select a row to modify your personal translations.

I haven't quite figured out how sending them to the maintainers would work just yet, and some of the syntax here might be incorrect. I'm just brainstorming.

EDIT: Something else I just thought about is that this will break the current feature that defaults to English if there is no translation. This will need to be handled in some way.

EDIT 2: Learned a bit more about tables. I believe that the language files will look like a lot of these:

`language["MENU_TITLE"]="Autoplugin"`

which can be referenced like this:

`language["MENU_TITLE"]`

I still believe putting it onto a table in necessary so the different languages can be easily compared.

**Comment by ONElua** [comment]
a table for each language!!!

**Comment by ONElua** [comment]
spanish = {MENU_TITLE="Autoplugin" ....}
english =  {MENU_TITLE="Autoplugin" ....}
...

and switch
language = spanish

then only show info with con language
language[MENU_TITLE]

**Comment by bamhm182** [comment]
For some reason I couldn't get it to work like that. With the code:
test = {TEST="My Test", TEST2="My Test 2"}
os.message(test[TEST])
os.message(test[TEST2])

It would crash stating that they were nil when os.message expects a string. There's not really a whole lot of reason to keep all of those tables in memory IMO. When the translate page loads, however, there will be a table for each language.

**Comment by ONElua** [comment]
another way
test = {

test1 =		"My Test",     -- important  the ,

}
os.mesage(test.test1)
