### ISSUE TITLE
AutoPlugin Latest GPU Crash

### ISSUE THREAD

**Issue by hi-nick** [theheroGAC/Autoplugin#14]
I went into the application, browsed the plugins available, and then I exited via START, then it resulted in a GPU Crash. It dumped the core file, but then the screen went blank but the back light is still on. I couldn't exit via the PS button, so I did a hard shutdown. Sadly, it isn't shutting down and the green power light is flashing. I cannot do anything. I tried booting into safe mode, but it's still on. I'm on 3.67 h-encore HENKAKU.

**Comment by theheroGAC** [comment]
What version of autoplugin do you use? What plug in have you installed?

**Comment by hi-nick** [comment]
Autoplugin 2.03, and my psvita is not turning on after charging it after letting the battery die. Won't boot into safe mode either.

**Comment by hi-nick** [comment]
I have nonpdrm, nopsmdrm, vsh menu (disabled), download enabler, and adrenaline double touch fix

**Comment by salmomascarenhas** [comment]
I also have the same problem (error) with the GPU after installing the only nonpdrm plugin.

**Comment by theheroGAC** [comment]
What firmware do you use and which version of autoplugin you use?

**Comment by theheroGAC** [comment]
new version is available v2.05

**Comment by salmomascarenhas** [comment]
I use firmware 3.68. I will try u new version. Thank u!
