### ISSUE TITLE
SD2VITA for UMA partition. 

### ISSUE THREAD

**Issue by Monumilnides** [theheroGAC/Autoplugin#146]
I have an official Sony 64GB memory and a micro SD 64GB, in my case it would be interesting to have the possibility of mounting the micro SD as UMA instead of UX0. Could you please add the necessary plugin for this?

**Comment by bamhm182** [comment]
All you should need to do is install the SD2VITA plugin, then return to the same place the installation option was, then you can configure the SD2VITA plugin and set it to whatever mount point you want. This is a new feature I added, so make sure you're up to date and check that it meets your needs.

**Comment by bamhm182** [comment]
Right this second, you need to reboot first. I submitted a pull request that will allow you to configure it before the first reboot.

**Comment by Monumilnides** [comment]
Thanks bamhm182!

**Comment by bamhm182** [comment]
No problem! It's available in the most recent version of Autoplugin available to everyone. Just tested it on my PSTV. Can we close this ticket?

**Comment by Monumilnides** [comment]
Thanks again to you two. It works impeccably. Tested on a PS vita slim 3.60 newly formatted. All green!
