### ISSUE TITLE
PKGJ config configuration

### ISSUE THREAD

**Issue by Schn1ek3** [theheroGAC/Autoplugin#155]
the config can be changed by hand on these 3 lines:

install_psp_as_pbp                  E-Boot or ISO
install_psp_psx_location          ux0 or uma0... 
no_version_check 

It would be nice if you can customize this about Autoplugin.

**Comment by ONElua** [comment]
Done https://github.com/theheroGAC/Autoplugin/commit/c4fbc37bd2be517f62384659bb3439a0b75878e7

**Comment by theheroGAC** [comment]
Autoplugin v3.73 available :)

**Comment by yexun1995** [comment]
So...Where can I get a config.txt file if I don't have one already?Just create an empty txt file manually?
And,if autoplugin don't provide PKGj's config.txt ,is it necessary to keep the line "Install config.txt for PKGJ v0.45+" in the language file?

**Comment by theheroGAC** [comment]
Use this https://nopaystation.com/pkgj/config.txt inside folder pkgj in ux0 or ur0

**Comment by yexun1995** [comment]
Thank you.

**Comment by ONElua** [comment]
best update your pkgj !!!
