### ISSUE TITLE
Plugin gamesd

### ISSUE THREAD

**Issue by Ramonziim** [theheroGAC/Autoplugin#16]
Estou com um problema. Fiz meu desbloqueio, mas não consigo fazer o ps vita ler meu cartão de memória. Pesquisando aqui, vi que precisa do plugin gamesd, mas ele não aparece no autoplugin pra instalar. Como faço para instalar esse plugin?

**Comment by theheroGAC** [comment]
Install this version https://github.com/theheroGAC/Autoplugin/releases/tag/3.00
