### ISSUE TITLE
script.lua error

### ISSUE THREAD

**Issue by yexun1995** [theheroGAC/Autoplugin#179]
![2019-01-26-134359](https://user-images.githubusercontent.com/13676949/51783149-b77d3280-2170-11e9-8bed-8feb0d1ebe20.png)
This problem occurs in the latest master branch.
When I delete the font file, connect to wifi and run Autoplugin, this error will occur.

**Comment by ONElua** [comment]
https://github.com/theheroGAC/Autoplugin/pull/180

**Comment by yexun1995** [comment]
Thank you. It works as expected.
