### ISSUE TITLE
v 3.72 miss charters on menu list

### ISSUE THREAD

**Issue by nictse2013** [theheroGAC/Autoplugin#187]
if system language is not english
last version hasn't this bug

**Comment by theheroGAC** [comment]
hi,your language?

**Comment by nictse2013** [comment]
> hi,your language?

chinese.

**Comment by theheroGAC** [comment]
test nightly https://github.com/theheroGAC/Autoplugin/blob/master/Nightly/RELEASE/Autoplugin%20Nightly.vpk
The problem solved?

**Comment by nictse2013** [comment]
> test nightly https://github.com/theheroGAC/Autoplugin/blob/master/Nightly/RELEASE/Autoplugin%20Nightly.vpk
> The problem solved?

I'm outside now,
I'll try it later!

**Comment by ONElua** [comment]
please send  screenshot...

**Comment by nictse2013** [comment]
3.73 still has this problem
i don't know where to upload the pic 
so i just describe it

when enter the app, just show 2 lines of words
"psvita
psp(adrenalin)"

u can move the cursor up and down the two lines, but just blank no any words....

**Comment by ONElua** [comment]
Uninstall&Reinstall

**Comment by nictse2013** [comment]
[
![capture](https://user-images.githubusercontent.com/6193203/52024365-9c793c80-253b-11e9-9d74-e1e8db527b72.png)
](url)


still same!

**Comment by yexun1995** [comment]
Delete the font.pgf file in ux0:data/autoplugin/font .
And,try to download it again.
https://github.com/theheroGAC/Autoplugin/blob/master/translations/font/font.pgf

**Comment by nictse2013** [comment]
i del the font
works fine!
thx all!

**Comment by nictse2013** [comment]
i del the font
works fine!
thx all!

**Comment by theheroGAC** [comment]
very good. closed issue
