### ISSUE TITLE
[Request] Add the plugin Camera Patch Lite for Adrenaline

### ISSUE THREAD

**Issue by SiTWulf** [theheroGAC/Autoplugin#197]
@theheroGAC you can add this plugin: https://github.com/Freakler/psp-camera_patch_lite
Is for Adrenanile and give real right stick camera controls to a few games in PSP.

This is the readme of the plugin:
camera_patch_lite
This plugin can add right analog stick support to PSP games on the Adrenaline eCFW.

Installation:
Copy the .prx & .ini files to your seplugins folder and add "ms0:/seplugins/camera_patch_lite.prx 1" to the game.txt file.

Notes:
This does not involve actual game patching but only shortcuts the already build-in camera controls of those games to the analog stick. Depending on the game this will work differently good or bad! Like sometimes there might be a small delay or you'll only be able to look left or right, but thats all game depending and better than nothing imo. Also if a game uses a trigger button + the left analog stick for camera movement you obviously won't be able to walk and move the camera at the same time for example.

Also some games are disabled by default in the .ini file due to the native patches by TheFlow. Use those plugins instead!

Demo:
https://www.youtube.com/watch?v=mcaOkqbq82c

The following Games are supported currently:
.hack//link.
007 - From Russia with love
50Cent BulletProof G-Unit Edition
Aliens vs. Predator Requiem
Ape Escape: On the Loose
Assassins Creed: Bloodlines (disabled by default)
Avatar The Game
Ben 10 Aien Force Vilgax Attacks
Ben 10 Ultimate Alien Cosmic Destruction
Crisis Core: Final Fantasy VII
Coded Arms
Dantes Inferno (dodge with stick)
Daxter
Final Fantasy Type0
Free Running
Ghostbusters: The Video Game
Gladiator Begins
God of War: Chains of Olympus (dodge with stick)
God of War: Ghost of Sparta (dodge with stick)
Grand Theft Auto Liberty City Stories (disabled by default)
Grand Theft Auto Vice City Stories (disabled by default)
Gun Showdown
Harvest Moon Hero of leaf valley
Indiana Jones and Staff of Kings
Iron Man
Iron Man 2
Jak & Daxter: The Lost Frontier
Manhunt 2
Marvel Ultimate Alliance
Marvel Ultimate Alliance 2
Medal of Honor Heroes
Medal of Honor Heroes 2
Metal Gear Solid - Peace Walker
Metal Gear Solid - Portable Ops
Miami Vice
Midnight Club LA Remix
Monster Hunter Freedom
Monster Hunter Freedom 2
Monster Hunter Freedom Unite
Monster Hunter Portable
Monster Hunter Portable 2nd
Monster Hunter Portable 3rd
Motorstorm Arctic Edge
Obscure: The Aftermath
Peter Jackson's King Kong
Pirates of the Caribbean - Dead man's chest
Prince of Persia - Revelations
Prince of Persia - Rival Swords
Ratatouille
Ratched & Clank Size Matters
Rengoku: The Tower of Purgatory
Rengoku II: The Stairway to Heaven
Resistance Retribution (disabled by default)
Secret Agent Clank
Silent Hill: Shattered Memories
Skate Park City
Spiderman 2
Spiderman 3
Spinout
Splinter Cell Essentials (disabled by default)
Star Wars Battlefront 2
Star Wars Battlefront 2 Elite Squadron
Star Wars Battlefront 2 Renegade Squadron
Star Wars Lethal Alliance
Syphon Filter Dark Mirror
Syphon Filter Logan's Shadow
The Godfather
The Simpsons The Game
The Warriors
Tom Clancy's Rainbow Six Vegas
Tom Clancy's Ghost Recon Advanced Warfighter 2
Tom Clancy's Ghost Recon Predator
The Legend Of Heroes: Trails in the Sky
The Legend Of Heroes: Trails in the Sky Second Chapter
Tomb Raider: Legends (disabled by default)
Tomb Raider: Anniversary (disabled by default)
Tony Hawk's Underground 2
Toy Story 3
Valkyria Chronicles 2
Valkyria Chronicles 3: Extra Edition
Vertigo
Currently not working Games:
- Call of Duty Roads to Victory
- Death Jr.
- Kingdom Hearts: Birth By Sleep
- The 3rd Birthday
- Super Monkey Ball Adventure
To add a game yourself just edit the camera_patch_lite.ini file with the TitleID and settings you want.

Have fun :)

Thanks & Greetings to: Team Molecule, The_FloW, reprep

**Comment by theheroGAC** [comment]
yes,in the next release :)
