### ISSUE TITLE
Problem with Turkish Translation

### ISSUE THREAD

**Issue by sakirasci** [theheroGAC/Autoplugin#198]
Hello! When I try to translate, I encounter two issues with the Turkish translation:

1. Turkish-exclusive characters (such as "Ş-ş", "İ-ı", "Ğ-ğ") won't show up in the application. They are replaced with an underscore symbol.
2. The Turkish translation file is saved as ENGLISH_GB.lua, even though the device language is set to Turkish. Naming the file as "TURKISH.lua" ends up with AutoPlugin not applying the translation.

Could you provide any solutions to those issues?

**Comment by ONElua** [comment]
First
Edit ENGLISH_GB.lua and replaced correct symbols...
and check autoplugin

**Comment by sakirasci** [comment]
>  english_gb uses the same id as turkish!!!!

So, it's not fixable? Is it because of Sony's not allocating Turkish a separate ID?

Even if I stick to english_gb.lua, Turkish-exlusive chars are still a problem. See the screenshots below. The text should read "Çıkış" but it is displayed as "Ç_k__", and in the file the text is fine. I added english_gb.lua file too.

[ENGLISH_GB.zip](https://github.com/theheroGAC/Autoplugin/files/2842700/ENGLISH_GB.zip)

![autoplugin tr 01](https://user-images.githubusercontent.com/41678204/52443797-b5837e00-2b37-11e9-8793-22528d28e381.png)
![autoplugin tr 02](https://user-images.githubusercontent.com/41678204/52443810-c3390380-2b37-11e9-8adc-87a49c3c6cbf.png)

**Comment by yexun1995** [comment]
Use a font file like us, it will display normally.
I am not sure if Turkish users really need to use extra font files.

**Comment by ONElua** [comment]
im fix 
if __LANG == "ENGLISH_GB" then __LANG = "TURKISH" end

but maybe need special font


PD:  I can send you a test vpk
but with the pvf font of the psvita

**Comment by ONElua** [comment]
Download the font.pgf file(here https://github.com/theheroGAC/Autoplugin/blob/master/translations/font/font.pgf ) and insert it in the path ux0:data/autoplugin/font 
![2019-02-08-124900](https://user-images.githubusercontent.com/25811032/52499507-33c83a80-2ba1-11e9-8c1f-d5628a5bafa3.png)

**Comment by bamhm182** [comment]
If that works, we can automatically load it like we do for Chinese.

**Comment by sakirasci** [comment]
Sorry for the late reply... You've already figured it out, it works so thanks! Once the Turkish translation is done, I'll let you know.

![2019-02-15-142400](https://user-images.githubusercontent.com/41678204/52856692-29c0b180-3136-11e9-9824-a4f407383e61.png)
