### ISSUE TITLE
Add netcheck_bypass plugin support by yifanlu

### ISSUE THREAD

**Issue by tmznix** [theheroGAC/Autoplugin#202]
Hi, first of all, thank you for your work on this app. Its fantastic.

Please, if possible, add support for the netcheck_bypass plugin by yifanlu (https://github.com/yifanlu/netcheck_bypass/releases)

I know its a per app plugin, but maybe its possible.
A syntax example for the Network media player app (UE) would be: (in ux0:tai/config.txt )
*PCSF00635 ux0:tai/netcheck_bypass.suprx

Thank you in advance.
Cheers.

**Comment by theheroGAC** [comment]
ok :) In the next release :)

**Comment by theheroGAC** [comment]
added https://github.com/theheroGAC/Autoplugin/releases/tag/3.77
