### ISSUE TITLE
autoplugin.lua script error

### ISSUE THREAD

**Issue by yexun1995** [theheroGAC/Autoplugin#204]
What I did:
1.Check for plugin updates(Vitagrafix was updated to 4.1.1)
2.Browse the **List of plugins ready to install**
When I browse to the line of VitaGrafix,push down button again,the bug occours.

My device Info:
PSV1000 3.60 enso
![2019-02-14-201919](https://user-images.githubusercontent.com/13676949/52786761-c469b380-3096-11e9-8800-3e901f4d9b97.png)

**Comment by theheroGAC** [comment]
thank you for bug report

**Comment by theheroGAC** [comment]
Fix in this release https://github.com/theheroGAC/Autoplugin/releases/tag/3.77
