### ISSUE TITLE
3.78 tai.lua script error

### ISSUE THREAD

**Issue by asakapa619** [theheroGAC/Autoplugin#210]
This is my 1st time using this plugin after running the app it always prompting "creating Config_backup.txt" and does not show plugins to install. how to fix this? my vita is 1000 3.60 enso, thanks
![img20190216153214](https://user-images.githubusercontent.com/47685889/52896773-1d585980-3207-11e9-8439-a8cdc7c2db77.jpg)

**Comment by theheroGAC** [comment]
create tai folder or delete config.txt in ux0

**Comment by asakapa619** [comment]
> 
> 
> create tai folder or delete config.txt in ux0

Ok i move my config.txt in ur0 and now it works! thanks! :)

**Comment by theheroGAC** [comment]
You have only tai folder in ur0?create tai folder in ux0

**Comment by raphfriend** [comment]
Same problem here. I havei tai folder on ur0 and ux0.

**Comment by raphfriend** [comment]
I made it and worked! 

> > create tai folder or delete config.txt in ux0
> 
> Ok i move my config.txt in ur0 and now it works! thanks! :)
> 
> btw i dont have sd2vita atm, and just want to ask why i cant choose a path to install my plugins? like ex. i want it to install in ux0 or ur0 by pressing L1 n R1 nothing happen doesn't work?

**Comment by asakapa619** [comment]
> 
> 
> You have only tai folder in ur0?create tai folder in ux0

i have both tai folder in ux0 and ur0, and for some reason autoplugin doesn't allow me to choose path, between ux0 and ur0, pressing L and R doesn't do anything...

**Comment by ONElua** [comment]
The ideal is to always use the config.txt of ur0:tai
and if you have sd2vita we are always going to use ur0
