### ISSUE TITLE
Problem with polish translation

### ISSUE THREAD

**Issue by kamkom21** [theheroGAC/Autoplugin#222]
Autoplugin has problem with polish language, cannot load because there is missing " in line 150 (on vitashell).

**Comment by roozx** [comment]
Im also contributing
"
ux0:/app/AUTOPLUGO/lang/POLISH.lua
POLISH.lua
115
unfinished string near "Dodatek PSP/ePSP aby uruchomic oficjalne NPDRM'y PS1/PSP bez pot.."

That's what i'm getting while opening the latest release of the app.

**Comment by ONElua** [comment]
please add "
at the end of the line in ux0:app/lang/polish
"Dodatek PSP/ePSP aby uruchomic oficjalne NPDRM'y PS1/PSP bez potrzeby poprawnej licencji .rif lub act.dat.

"Dodatek PSP/ePSP aby uruchomic oficjalne NPDRM'y PS1/PSP bez potrzeby poprawnej licencji .rif lub act.dat." <---

**Comment by theheroGAC** [comment]
Please use this file https://github.com/theheroGAC/Autoplugin/blob/master/lang/POLISH.lua thank you @ONElua

**Comment by theheroGAC** [comment]
fixed in new version 3.80 https://github.com/theheroGAC/Autoplugin/releases/download/3.80/Autoplugin.vpk
