### ISSUE TITLE
Installed Plugins List Disappears

### ISSUE THREAD

**Issue by Chxco** [theheroGAC/Autoplugin#223]
I recently manually installed a plugin not listed on Autoplugin and it seems to completely erase the list of installed plugins on the app. All of plugins function normally, but I can no longer uninstall plugins with the app.

**Comment by ONElua** [comment]
show your config.txt (ur0&ux0)

**Comment by Chxco** [comment]
[config.txt](https://github.com/theheroGAC/Autoplugin/files/2921052/config.txt)

I don't have a tai folder in ux0. The plugin I installed manually is buttonswap.

**Comment by ONElua** [comment]
""but I can no longer uninstall plugins with the app."""
press L/R in unnistall secction

**Comment by Chxco** [comment]
I've already tried that prior to posting the questions. The ur0 section is blank.
