### ISSUE TITLE
Error code 303 with sd2vita.lua

### ISSUE THREAD

**Issue by popoblito** [theheroGAC/Autoplugin#231]
Hi, I tried to install your autoplugin on my Vita (3.60) and this error appears, what should I do?
![unnamed](https://user-images.githubusercontent.com/48367747/54056943-d6e89000-41f1-11e9-803f-ffae050fd9e6.jpg)

**Comment by theheroGAC** [comment]
If you have ur0: tai / store.config.txt
and show you files
ur0: tai / config.txt
ur0: tai / store_config.txt
