### ISSUE TITLE
VitaStick auto install on open AutoPlugin

### ISSUE THREAD

**Issue by SiTWulf** [theheroGAC/Autoplugin#242]
For some reason, when i open AutoPlugin 3.84 they auto install VitaStick App automatically, every time i exit from AutoPlugin need to uninstall VitaStick...

**Comment by darkkomdld** [comment]
Same here and i need help because all other puglins start to fail and the console start to do weird staff i cant even play any way or move normally in the directory. It just break the console for me.

**Comment by darkkomdld** [comment]
yea i even uninstall it from the urx tai text, and when its installed again and again it inst the plugin just the vpk all the time installing. I got other problems along side this one. Im 3.60 but i can find the repach folders  for 3.65 in pkgj, i can´t use almost any plugin, vitabright and others, correctly installed dont trigger.  Sometimes  i cant move through menu  or open bubbles. Please anyway to fix this??? can u erase that virus vitastick??

**Comment by ONElua** [comment]
Fix https://github.com/theheroGAC/Autoplugin/pull/243
Wait :D

**Comment by theheroGAC** [comment]
New version available thank you @ONElua https://github.com/theheroGAC/Autoplugin/releases/tag/3.85
