### ISSUE TITLE
All App Text Transparent?

### ISSUE THREAD

**Issue by wiggehhh** [theheroGAC/Autoplugin#245]
Hi All,

The issue is that all text within the app appears to be transparent (and not white, like it was before). I have used the app without issue for several months but this has happened ever since I recently updated - which I was prompted to do!

I have attached some screenshots of what I can see on my Vita:

![IMG_3392](https://user-images.githubusercontent.com/49622758/56099289-c4edc180-5f02-11e9-81b3-c97eebca5da4.jpeg)
![IMG_3388](https://user-images.githubusercontent.com/49622758/56099292-d1721a00-5f02-11e9-929f-0f4288710daf.jpeg)
![IMG_3389](https://user-images.githubusercontent.com/49622758/56099293-d1721a00-5f02-11e9-8be3-fa6967e82eff.jpeg)
![IMG_3390](https://user-images.githubusercontent.com/49622758/56099294-d20ab080-5f02-11e9-882f-69523d1556b7.jpeg)
![IMG_3391](https://user-images.githubusercontent.com/49622758/56099295-d20ab080-5f02-11e9-9434-d966c80e3b7b.jpeg)

I have tried many different ways to fix this (including re-installing multiple times) but no luck... I also can't find anything about this online.

Please let me know what you think.

Thanks!

**Comment by yexun1995** [comment]
Delete the font file in ux0:data/autoplugin/font 
Then,if you need to use a font file,re-download the font file with your pc and copy it into that folder.
(Link  https://github.com/theheroGAC/Autoplugin/blob/master/translations/font/font.pgf )

**Comment by theheroGAC** [comment]
Yes the problem is font.pgf
