### ISSUE TITLE
add this plugin?

### ISSUE THREAD

**Issue by Dankfambo25** [theheroGAC/Autoplugin#256]
udcd-uvc screen off during use

https://old.reddit.com/r/vitahacks/comments/as2ap8/xerpis_usb_streaming_udcd_uvc_v_12_patched_for/

**Comment by theheroGAC** [comment]
Added. Use plugin update control from Autoplugin :)

**Comment by Dankfambo25** [comment]
> Added. Use plugin update control from Autoplugin :) and install new version :)

thanks hero for the update. i found out about this plugin here: https://www.reddit.com/r/vitahacks/comments/bsw599/found_a_way_to_use_the_psvita_udcduvc_while_the/

but the only issue that plugin works with oled 

someone made a patch that works with lcd here: https://drive.google.com/file/d/1DJvtlQOkkUNP5DCZY3a73OkXhtbOT1j2/view?usp=sharing

source is in the comment section: https://old.reddit.com/r/vitahacks/comments/as2ap8/xerpis_usb_streaming_udcd_uvc_v_12_patched_for/

so if you could separate and name the plugins for oled and the other lcd

**Comment by theheroGAC** [comment]
In the next update added your request :)

**Comment by Dankfambo25** [comment]
> In the next update added your request :)

one more thing for the lcd and oled plugins could you change the description to "Enables you to stream your Vita screen to your PC with the screen off"

**Comment by theheroGAC** [comment]
> > In the next update added your request :)
> 
> one more thing for the lcd and oled plugins could you change the description to; Enables you to stream your Vita screen to your PC with the screen off. don't do this with the regular xerpi plugin only the lcd and oled one

https://github.com/theheroGAC/Autoplugin/releases/tag/3.91

**Comment by Dankfambo25** [comment]
> > > In the next update added your request :)
> > 
> > 
> > one more thing for the lcd and oled plugins could you change the description to; Enables you to stream your Vita screen to your PC with the screen off. don't do this with the regular xerpi plugin only the lcd and oled one
> 
> https://github.com/theheroGAC/Autoplugin/releases/tag/3.91

hey dude xerpi just added his own version of the on/off screen then you capture on pc. so can you delete the old ones and add the new ones here :https://github.com/xerpi/vita-udcd-uvc/releases/tag/1.4 along with removing the old description and add in the new description of what xerpi said on each plugin. thanks.
