### ISSUE TITLE
doesn't work with tf-card-plugin-tool

### ISSUE THREAD

**Issue by NeonLightning** [theheroGAC/Autoplugin#26]
when you run tf-card-plugin-tool it replaces ux0:tai/config.txt with a directory called config.txt
autoplugin(aswell as every other plugin manager i've seen) doesn't handle that properly.
spits out
`tai.lua`
`47`
`bad argument #1 to 'lines' (ux0:tai/config.txt: is a directory)`

**Comment by ONElua** [comment]
please send me capture!!!!
then TF card creates a completed folder ux0:tai/config.txt ??
