### ISSUE TITLE
Update AnalogsEnhancer with my mod

### ISSUE THREAD

**Issue by Yoti** [theheroGAC/Autoplugin#266]
Due the system wide plugin nature (this is kernel one) much better to store settings in the system partition. So, I made a such mod: https://github.com/Yoti/AnalogsEnhancer

**Comment by theheroGAC** [comment]
Ok update now thank you

**Comment by theheroGAC** [comment]
Now available thank you https://github.com/theheroGAC/Autoplugin/releases/download/3.95/Autoplugin.vpk
