### ISSUE TITLE
Installation of udcd_uvc for OLED and LCD does not succeed

### ISSUE THREAD

**Issue by d-rez** [theheroGAC/Autoplugin#267]
# v3.94

Not sure exactly what this is caused by, for some reason repository source doesn't match with what I'm seeing on my Vita?

I'm trying to install udcd_uvc_lcd (but same thing happens for oled plugin version - did it for a test). Pure udcd_uvc plugins install succeeds OK

Basically:

* No skprx plugin file never gets copied over to /tai
* Filenames in my ux0:app/AUTOPLUG0/resources/plugins do not match the ones in repo. 
  * Ones I have in the folder on Vita are:
    * udcd_uvc_lcd_off.skprx
    * udcd_uvc_oled_off.skprx
  * Ones [in the repo are](https://github.com/theheroGAC/Autoplugin/tree/master/resources/plugins):
    * udcd_uvc_lcd.skprx
    * udcd_uvc_oled.skprx
    * This matches what I see in [plugins.lua](https://github.com/theheroGAC/Autoplugin/blob/master/plugins/plugins.lua)
* Installing plug-in causes bad entry to be added to config.txt, depending on version. Note how .skprx extension is missing, plugin gets highlighted in orange and is never loaded
    * udcd_uvc_lcd_off
    * udcd_uvc_oled_off

No idea what's going on here

**Comment by theheroGAC** [comment]
new release in few minutes

**Comment by theheroGAC** [comment]
fixed https://github.com/theheroGAC/Autoplugin/releases/download/3.95/Autoplugin.vpk
Thank you :)
