### ISSUE TITLE
Update for Spanish Languague

### ISSUE THREAD

**Issue by L89David** [theheroGAC/Autoplugin#277]
Hi! I've wanted to help a little bit in this amazing project by just updating the spanish languague in Autoplugin. (Two plugin descriptions). Thanks!!
[SPANISH.txt](https://github.com/theheroGAC/Autoplugin/files/3563514/SPANISH.txt)

**Comment by thedevil4k** [comment]
I have translate Autoplugin to Spanish , you can download SPANISH.lua from my drive link : https://drive.google.com/file/d/1aY1J2iZxyh8gQi8YtekBvu2g_zuUzQZt/view?usp=sharing

The 2 plugin descriptions have been translated to Spanish .
