### ISSUE TITLE
Polish translation bug underscore instead of diacritic characters

### ISSUE THREAD

**Issue by olokos** [theheroGAC/Autoplugin#279]
Hey,

So since a while now polish translation has broken diacritic characters, namely instead of characters like ą, ę, ć etc. there are underscores instead.

Before there was no diacritic characters which wasn't ideal, but now instead of those letters there are underscores everywhere. Maybe those characters are missing in the font used by Autoplugin?

**Comment by yexun1995** [comment]
Maybe you need to use the font.pgf file.

https://github.com/theheroGAC/Autoplugin#small-note-for-the-translation-of-the-language-for-chinese-friends

**Comment by olokos** [comment]
spot on, that was it, haven't expected this to be useful for non chinese languages :p

**Comment by olokos** [comment]
Maybe it would be possible to update the readme, mentioning that it's not only for chinese people? We could then close the issue.

**Comment by olokos** [comment]
I have just created a pull request about this
https://github.com/theheroGAC/Autoplugin/pull/280

**Comment by olokos** [comment]
It has been merged so I'm closing the issue now.
