### ISSUE TITLE
NoLockScreen

### ISSUE THREAD

**Issue by Yoti** [theheroGAC/Autoplugin#281]
Latest AutoPlugin has unknown version of this plugin. Plz update to official v2: https://github.com/TheOfficialFloW/VitaTweaks/releases/tag/NoLockScreen

**Comment by theheroGAC** [comment]
ok thank you

**Comment by theheroGAC** [comment]
fixed on Autoplugin 4.01

**Comment by olokos** [comment]
I don't really know why is that, but on Vita 3.65 Enso using Autoplugin 4.01 it still loads a broken version of NoLockScreen for some reason.
Here are checksums of the broken nolockscreen.suprx installed currently by 4.01 
CRC32: A5F62214
MD5: 79C9504ADD6D1AF555E69E991074CBCF
SHA-1: 5A14EFBC89719CB4945DF10FA883937CEB8C4FC7

and here are the checksums of the actual up-to-date nolockscreen.suprx, which appears to be exactly the same as the one in this repo master/resources/plugins, but it's not being used
CRC32: 10894703
MD5: D86E2D88326426AC9E1B301A7B4B9775
SHA-1: 37F11AF4CC8CFA2E38A80751513FBDF0690AA5C3

Interesting what's going on here, but the one actually installed by Autoplugin 4.01 is not 10894703 but A5F62214, I tested it a few times and it always installs A5F62214 anyway.

**Comment by ONElua** [comment]
Its true, but the oficial version is crc32 A5F62214 for the repo of the Flow

**Comment by olokos** [comment]
Nonetheless A5F62214 is not the latest release of the source code, I think the goal of autoplugin is to always download the most updated plugins and install them with ease, right? :p

**Comment by ONElua** [comment]
@olokos you can share the link

**Comment by theheroGAC** [comment]
@olokos fix on Autoplugin 4.02 https://github.com/theheroGAC/Autoplugin/releases/tag/4.02

**Comment by olokos** [comment]
Works great now, thanks!
The issue can now be closed
