### ISSUE TITLE
Needs cancel update option

### ISSUE THREAD

**Issue by EzekielLati** [theheroGAC/Autoplugin#29]
I wanted to cancel the update of autoplugin because the download can be slow sometimes. I get like 100kb/s, I had to download here and use a vpn. Idk if github has issues on sea or ph server though

**Comment by theheroGAC** [comment]
Fixed in version 3.12?

**Comment by EzekielLati** [comment]
It's faster now

**Comment by theheroGAC** [comment]
Thank you for your bug report :+1:
