### ISSUE TITLE
rePatch 2.71

### ISSUE THREAD

**Issue by Yoti** [theheroGAC/Autoplugin#290]
Please add rePatch 2.71 (https://github.com/dots-tb/rePatch-reDux0/releases/tag/2.71) along with 3.00 'cause newer one has at least one critical bug (https://github.com/dots-tb/rePatch-reDux0/issues/41).

**Comment by theheroGAC** [comment]
ok thank you,in the next big update :)

**Comment by theheroGAC** [comment]
solved
