### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by RealYoti** [theheroGAC/Autoplugin#308]
1) Replace Rinnegatamante/AnalogsEnhancer with https://github.com/Yoti/AnalogsEnhancer/tree/v1.1-ur0
2) Hack-Usagi/AnalogStickDisable is v1.1 and not v1.2. V1.2 is my mods https://github.com/Hack-Usagi/AnalogStickDisable/pull/3
3) VitaTweaks with 3.72 and 3.73 support:
[download_enabler.zip](https://github.com/theheroGAC/Autoplugin/files/4007372/download_enabler.zip)
[nolockscreen.zip](https://github.com/theheroGAC/Autoplugin/files/4007373/nolockscreen.zip)
[notrophymsg.zip](https://github.com/theheroGAC/Autoplugin/files/4007374/notrophymsg.zip)

**Comment by theheroGAC** [comment]
Now available https://github.com/theheroGAC/Autoplugin/releases/tag/4.16
thank you :)
