### ISSUE TITLE
Simplified Chinese translation error

### ISSUE THREAD

**Issue by psv1kdump** [theheroGAC/Autoplugin#34]
Simplified Chinese translation error“unexpected symbol near i",upsite view location"ux0:/app/AUTOPLUG0/lang/CHINESE_S.txt.when remove the CHINESE_S.txt will running well.

**Comment by wetor** [comment]
Got the same!

**Comment by theheroGAC** [comment]
please test this version https://mega.nz/#!XD4C3IZA!OTj_7-kYI5bvM8Sv6Mzyse_su-EO1wDPKHa-akjhs34

**Comment by theheroGAC** [comment]
Format utf-8

**Comment by psv1kdump** [comment]
YUP!If put the vitashell font file inside AUTOPLUGIN font folder it will fix  Font missing words problem.

**Comment by theheroGAC** [comment]
please test this https://mega.nz/#!HGhzEBKb!xBrfUPMU-uhr1wJn9UJ5WlBu-w9yEs3r0JF2B2ywrpI
