### ISSUE TITLE
Traditional Chinese

### ISSUE THREAD

**Issue by taiwan-no1** [theheroGAC/Autoplugin#37]
![image](https://user-images.githubusercontent.com/42412705/44153713-8ed72306-a0db-11e8-9e84-7093e91a5571.png)

![image](https://user-images.githubusercontent.com/42412705/44153778-b6c8a268-a0db-11e8-8c01-4efec38a7901.png)

![image](https://user-images.githubusercontent.com/42412705/44153869-e83089c4-a0db-11e8-8c8d-064fd315bce7.png)

**Comment by theheroGAC** [comment]
Work now?

**Comment by taiwan-no1** [comment]
yes ! Work

**Comment by theheroGAC** [comment]
Thank you.Please download for me chinese_t.txt language

**Comment by taiwan-no1** [comment]
chinese_t.txt --->
https://mega.nz/#!wvplURAB!AamluC_dyNEeoMDV9j_K4TMQRY_NkKBAJd2nHSOT3Sg

**Comment by theheroGAC** [comment]
Thank you.Next release 3.14 in few minutes
