### ISSUE TITLE
CHINESE_S.txt unexpected symbol near i error

### ISSUE THREAD

**Issue by psv1kdump** [theheroGAC/Autoplugin#49]
![img_20180911_020000](https://user-images.githubusercontent.com/38326397/45315382-e0f14500-b566-11e8-9d3e-34b6676ee48a.jpg)

version 3.28 & 3.29 come out this error,version 3.27 is ok.

**Comment by theheroGAC** [comment]
Please reinstall this version https://github.com/theheroGAC/Autoplugin/releases/download/3.29/Autoplugin.vpk

**Comment by psv1kdump** [comment]
Done，fix the bug.
