### ISSUE TITLE
Adrenaline startup plugin 

### ISSUE THREAD

**Issue by HtheB** [theheroGAC/Autoplugin#5]
From the readme at https://github.com/TheOfficialFloW/Adrenaline : 
**Adrenaline has been redesigned in 6.61 Adrenaline-6, so you'd need to launch Adrenaline twice everytime you reboot your device. To get rid of that, simply write this line to *KERNEL:**

*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx

[adrenaline_kernel.zip](https://github.com/theheroGAC/Autoplugin/files/1975773/adrenaline_kernel.zip)

Would be nice to have this in the Autoplugin for Adrenaline users :)

**Comment by theheroGAC** [comment]
It is already included
