### ISSUE TITLE
VitaBright stats it is compatible with 3.68, but Autoplugin states it needs 3.60?

### ISSUE THREAD

**Issue by mvaneijgen** [theheroGAC/Autoplugin#52]
> This plugin is only compatible with OLED model Vita consoles. Tested to be functional on 3.60 Ensō and now 3.68 h-encore.

https://github.com/devnoname120/vitabright

Because if the really sparse documentation of VitaBright I thought and downloaded AutoPlugin, it seems like an easier way to manage vita plugins, but is it me or is there an old version of VitaBright in this plugin?

Are there any plans for including upgrades to AutoPlugin if developers release a new version of there plugin?

**Comment by theheroGAC** [comment]
All plugins are updated to the latest version. If it works on 3.68 it is only the writing to be deleted

**Comment by mvaneijgen** [comment]
@theheroGAC I see you just updated the app, but somehow the message is still the same. It looks like your app does a check on your device, because it will just not install. Yesterday I got the message in the pop up:

> Vitabright is only for 3.60

And now I get 

> Vitabright is only for 3.60/H-encore 3.68, but I can only hit `Ok` and nothing will happen. It just opens an closes the pop up 

![See screenshots](https://i.imgur.com/M64xjbz.jpg)

**Comment by theheroGAC** [comment]
Thank you for your report.New version 3.32 available in few minutes
