### ISSUE TITLE
"Check for Plugins Updates" doesn’t work when wired connection(PSTV).

### ISSUE THREAD

**Issue by rakujong** [theheroGAC/Autoplugin#58]
"System Message - wifi is required" is display.
"Check for Plugins Updates" works only when connecting to the Internet via Wi-Fi.

**Comment by ONElua** [comment]
pleae try
https://www.dropbox.com/s/sh0aw9zmlh9ybf3/Autoplugin.vpk?dl=0
I wait your answer
