### ISSUE TITLE
ds3plugin autoplugin

### ISSUE THREAD

**Issue by irshadhashmi** [theheroGAC/Autoplugin#6]
i play my games ps3 controller on playstation tv work perfectly when i install autoplugin ur0 or ux0 my ds3 controller not work properly in gaming. live screen analog work but in gaming and touch pad activeted analog not work

**Comment by irshadhashmi** [comment]
i test new controller same problem,and all controller work my ps3 in perfect

**Comment by theheroGAC** [comment]
this can be a problem with the plugin. The original plugin is in beta.I will check the autoplugin application and plugin ds3vita

**Comment by irshadhashmi** [comment]
I delete ds3 and ds4 plugins cong. And file work perfectly
