### ISSUE TITLE
3.57 unexpected symbol near…

### ISSUE THREAD

**Issue by frstrikerman** [theheroGAC/Autoplugin#79]
After upgrading to 3.57 and also reinstalling autoplugin I got this error

![2018-11-11-094022](https://user-images.githubusercontent.com/19488257/48310872-6fe60200-e596-11e8-9486-8aaf76c25095.jpg)

**Comment by theheroGAC** [comment]
Please re-download version 3.57

**Comment by frstrikerman** [comment]
I did an upgrade from autoplugin itself an since I got this error I uninstall it a download the vpk and in both case I got this error
here is the md5sum `82ab991a78c0728cdb0a412c1d3678f2`

**Comment by frstrikerman** [comment]
So I redownload it from your link and my md5sum is now `fb99bd6eadbfa7a8fa0d6c38f1de4231`

**Comment by frstrikerman** [comment]
the issue is solved thanks
