### ISSUE TITLE
vitabright reset

### ISSUE THREAD

**Issue by eiiiiix** [theheroGAC/Autoplugin#8]
I had a custom gamma filter and after using this to download some plugins and autoadd to a config it reset the gamma
It should check if configs exist before overwriting them

**Comment by theheroGAC** [comment]
In the next update I will try to make a backup of the entire tai folder in case of problems

**Comment by eiiiiix** [comment]
ok
time to move my plugins folder to the root of ur0: so i can save 57mb then :P

**Comment by theheroGAC** [comment]
releases new version that automatically saves the tai folder(v1.07)
