### ISSUE TITLE
Instaled plugins not showing

### ISSUE THREAD

**Issue by Doredialilligan** [theheroGAC/Autoplugin#98]
Hi :)
I installed Autoplugin after all my plugins were installed manually in my PSVita. When I open the app, it doesn't show any of my manually installed plugins. I tried copying my config.txt to ux0:app/resources/config/ but it doesn't work.

I have all my plugins in ur0:tai/, is there any solution?

**Comment by theheroGAC** [comment]
to find your plugins, autoplugin creates a backup copy of the config.txt file in ur0: tai.The program currently does not recognize those installed manually without autoplugin

**Comment by obinta** [comment]
Please help me my autoplugin opens but doesnt show the plugins for me to open

**Comment by obinta** [comment]
It was opening before now but later it started this problem.it opens up but i see nothing
